require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'db/**/*'
    - 'Rakefile'
    - 'config/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
  UseCache: false
  TargetRailsVersion: 6.0
  TargetRubyVersion: 2.7.0

Capybara/FeatureMethods:
  EnabledMethods: ['feature', 'scenario', 'xscenario','given', 'background']

Layout/DotPosition:
  EnforcedStyle: trailing

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'feature', 'scenario', 'let']

RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Style/Documentation:
  Enabled: false
