services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
  server:
    image: .
    container_name: watch_tower
    ports:
      - "3000:3000"
    environment:
      - BUNDLE_PATH=vendor/bundle
      - BUNDLE_DISABLE_SHARED_GEMS=1
      - RUBYOPT=-W0
    volumes:
      - .:/var/www/watch_tower:Z
    working_dir: /var/www/watch_tower
    command: bundle exec rails s -b 0.0.0.0
    depends_on:
      - db
